spring.application.name=infytel-friend-family
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:friendFamilydb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=create
server.port=8081
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.cloud.consul.config.format=YAML
spring.config.import=consul:
spring.cloud.consul.discovery.hostname=localhost
#server.address=127.0.0.1
#spring.cloud.consul.discovery.prefer-ip-address=true

#management.endpoints.web.exposure.include=env,health
#management.endpoints.web.base-path=/actuator
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always
## Explicitly tell Consul where to look for health checks
#spring.cloud.consul.discovery.health-check-path=${management.endpoints.web.base-path}/health
#spring.cloud.consul.discovery.health-check-interval=10s