spring.application.name=infytel-customer
spring.config.import=consul:
#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500

# Tell Spring Cloud Consul to parse KV values as YAML
spring.cloud.consul.config.format=YAML
spring.cloud.consul.discovery.hostname=localhost


friend.uri=http://localhost:8081/customers/
plan.uri=http://localhost:8093/plans/

#logging.level.org.springframework.cloud.consul=DEBUG
#logging.level.org.springframework.cloud.bootstrap=DEBUG
#logging.level.org.springframework.cloud.consul.config=DEBUG
#logging.level.org.springframework.boot.context.config=DEBUG
#logging.level.org.springframework.web.client.RestTemplate=DEBUG
#
#management.endpoints.web.exposure.include=env,health
#management.endpoints.web.base-path=/actuator
# Force Spring Cloud LoadBalancer to initialize its routes immediately at startup

#### For resilience 4j & Circuit Breaker ####
# This below property is the threshold percentage beyond which if the failure in the number of calls then the circuit will be moved to open state to close state
resilience4j.circuitbreaker.instances.customerService.failure-rate-threshold=50 
# When the below is true SpringBoot will expose the circuit breaker's health status via Spring Boot Actuator
resilience4j.circuitbreaker.instances.customerService.register-health-indicator=true
# This is the property that denotes the minimum number of calls that must be made in closed state before the circuit is open
resilience4j.circuitbreaker.instances.customerService.sliding-window-size=5
# This is the property which specifies the minimum number of calls to be made in open state.
resilience4j.circuitbreaker.instances.customerService.permitted-number-of-calls-in-half-open-state=3
# This property specifies the time the circuit breaker should wait before moving from open to half open state
resilience4j.circuitbreaker.instances.customerService.wait-duration-in-open-state=10s
# This property means if it is set to true ut can automatically move from open to half open
resilience4j.circuitbreaker.instances.customerService.automatic-transition-from-open-to-half-open-enabled=true