spring.application.name=infytel-customer
spring.config.import=consul:
#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500

# Tell Spring Cloud Consul to parse KV values as YAML
spring.cloud.consul.config.format=YAML

friend.uri=http://localhost:8081/customers/
plan.uri=http://localhost:8093/plans/

#logging.level.org.springframework.cloud.consul=DEBUG
#logging.level.org.springframework.cloud.bootstrap=DEBUG
#logging.level.org.springframework.cloud.consul.config=DEBUG
#logging.level.org.springframework.boot.context.config=DEBUG
#logging.level.org.springframework.web.client.RestTemplate=DEBUG
#
#management.endpoints.web.exposure.include=env,health
#management.endpoints.web.base-path=/actuator
