spring.application.name=infytell-calldetails
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=create
spring.cloud.consul.discovery.hostname=localhost
server.port=8092
spring.config.import=consul:
spring.cloud.consul.config.format=YAML
#spring.cloud.consul.config.defaultContext=application